#NOTE: UPDATE FLAGS LATER
DEP_FLAGS = -MMD -MP
CFLAGS = -Wall -Wextra # -Werror
CC = cc
INCLUDE_DIRS = ./include

# [c] do not warn about creation of file
# [r] eplace existing or insert new file(s) into the archive
# [U] set time stamps needed for replacement using make's archive(member) function
# [v] show added entries in archive file
ARFLAGS = rcU
NAME := libft.a

BUILD_DIR := ./build

SRC := \
ft_atoi.c    \
ft_bzero.c   \
ft_ctype.c   \
ft_memset.c  \
ft_strlen.c  \
ft_strnstr.c \

#------------------------------------------------------------#
INCLUDE_FLAGS = $(addprefix -I, $(INCLUDE_DIRS))
OBJECT := $(patsubst %.c, $(BUILD_DIR)/%.o, $(SRC))
# DEPS := $(OBJECT:.o=.d)

all: $(BUILD_DIR) $(NAME)($(OBJECT))

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(NAME):
	$(AR) $(ARFLAGS) $(NAME)

$(OBJECT): $(SRC)
	$(CC) $(DEP_FLAGS) $(CFLAGS) $(INCLUDE_FLAGS) -c $< -o $@

clean:
	rm -r $(BUILD_DIR)

fclean: clean
	rm $(NAME)

TESTER := test.c
TEST_OUTPUT := test
test:
	$(CC) $(TESTER) libft.a -o $(TEST_OUTPUT) $(INCLUDE_FLAGS)
	./test

re: fclean all

.PHONY: all clean fclean re test setup-env

include $(DEPS)

# setup-env:
# 	@printf "# generated by makefile: \n \
# 	$(BUILD_DIR) \n \
# 	$(NAME) \n \
# 	$(TEST_OUTPUT) \n \
# 	" > .gitignore
#
